import { Ubuntu } from "next/font/google";
import "./globals.css";


const ubuntu = Ubuntu({ subsets: ["latin"], weight: ["300", "400", "500", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <navbar className="fixed w-full md:">
          <div className="overflow-hidden">

          </div>
        </navbar>
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
          {children}
        </main>
        <footer>
          <div class="relative h-32 w-32 ...">
            <div class="absolute inset-x-0 bottom-0 h-16">Footer to come</div>
          </div>
        </footer>

      </body>
    </html>
  );
}
